<div id="contenido-libre">

	<p>Aprovechando su visita le ofrecemos sin cargo alguno, demos de nuestros desarrollos en Excel y presentaciones utilizadas en las sesiones de capacitación que brindamos a nuestros clientes.</p>

	<p>Solo debe hacer clic sobre el ejemplo deseado y completar un breve formulario.</p>

	<h2>MS-Office</h2>
	<ul>
		<li><a href="Guia_Aplicaciones_Especiales-Classnet.xls">Guía de Aplicaciones Especiales</a></li>
		<li><a href="Simulador_Punto_Equilibrio-Classnet.xls">Simulador dinámico para análisis de Puntos de Equilibrio</a></li>
		<li><a href="Presupuesto_Financiero-Classnet.xls">Presupuesto Financiero</a></li>
		<li><a href="Formulario de Evaluacion-V1-Classnet.xls">Formulario de Evaluación de Desempeño, Capacitación y Servicios</a></li>
	</ul>

	<h2>SAP</h2>
	<ul>
		<li><a href="SAP-Curso-Proceso-Compras-Classnet.pps">Curso de Proceso de Compras en sistemas ERP</a></li>
		<li><a href="SAP-MIRO-Create Variant-Classnet.pdf">MIRO - Crear una nueva Variante</a></li>
	</ul>

	<p class="small">Si lo desea, envíenos sus inquietudes y necesidades a <?php add_email('contacto','e-classnet')?> y le haremos llegar nuestra propuesta de solución a la brevedad.</p>

</div>
