
	<!-- FOOTER -->
	<div id="footer">
		<div class="center">
			<div class="left">
				<?php add_email('contacto', 'e-classnet') ?>
				<p>(549) 11 6514-4040</p>
			</div>
			<div id="copyright">
				Copyright &copy; 2009-2016 Classnet Technology<br />
				Todos los derechos reservados
			</div>
			<div id="w3c">
				<a href="http://validator.w3.org/check?uri=referer">
					<img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" height="31" width="88" />
				</a>
			</div>
		</div>
	</div>